routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AbsensiStaffController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RfidController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['auth', 'isLogin'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/update', [DashboardController::class, 'update'])->name('profile.update');

    //Route Data Permission
    Route::resource('permission', PermissionController::class);

    //Route Data Role
    Route::resource('role', RoleController::class);

    //Route Data Users
    Route::post('/user/import', [UserController::class, 'import'])->name('user.import');
    Route::get('/user/download', [UserController::class, 'download'])->name('user.download');
    Route::get('/dump/user', [UserController::class, 'dump'])->name('user.dump');
    Route::get('/user/{user:id}/status', [UserController::class, 'status'])->name('user.status');
    Route::get('/user/islogin', [UserController::class, 'islogin'])->name('user.islogin');
    Route::post('/user/{user:id}/delete', [UserController::class, 'delete'])->name('user.delete');
    Route::resource('user', UserController::class);

    //Route Data Kelas
    Route::post('/kelas/import', [KelasController::class, 'import'])->name('kelas.import');
    Route::get('/kelas/download', [KelasController::class, 'download'])->name('kelas.download');
    Route::get('/kelas/siswa', [KelasController::class, 'getSiswa'])->name('kelas.siswa');
    Route::post('/kelas/kenaikan', [KelasController::class, 'kenaikan'])->name('kelas.kenaikan');
    Route::resource('kelas', KelasController::class);

    //Route Data Siswa
    Route::get('/dump/siswa', [SiswaController::class, 'dump'])->name('siswa.dump');
    Route::get('/siswa/{siswa:id}/activated', [SiswaController::class, 'activated'])->name('siswa.activated');
    Route::get('/siswa/{siswa:id}/export', [SiswaController::class, 'export'])->name('siswa.export');
    Route::post('/siswa/{siswa:id}/delete', [SiswaController::class, 'delete'])->name('siswa.delete');
    Route::resource('siswa', SiswaController::class);

    //Route Data Jadwal
    Route::get('/jadwal/set', [JadwalController::class, 'set'])->name('jadwal.set');
    Route::resource('jadwal', JadwalController::class);

    //Route Data Holiday
    Route::resource('holiday', HolidayController::class);

    //Route Data Device
    Route::post('/device/{device:id}/change', [DeviceController::class, 'change'])->name('device.change');
    Route::resource('device', DeviceController::class);

    //Route Data Rfid
    Route::resource('rfid', RfidController::class);

    //Route Data History
    Route::resource('history', HistoryController::class);

    //Route Data Absensi
    Route::get('/absensi/export', [AbsensiController::class, 'export'])->name('absensi.export');
    Route::get('/absensi/report', [AbsensiController::class, 'report'])->name('absensi.report');
    Route::get('/absensi/export-report', [AbsensiController::class, 'generate'])->name('absensi.generate');
    Route::get('/absensi/{absensi:id}/change', [AbsensiController::class, 'change'])->name('absensi.change');
    Route::resource('absensi', AbsensiController::class);

    //Route Data Absensi Staff
    Route::get('/absensi-staff/export', [AbsensiStaffController::class, 'export'])->name('absensi-staff.export');
    Route::get('/absensi-staff/report', [AbsensiStaffController::class, 'report'])->name('absensi-staff.report');
    Route::get('/absensi-staff/export-report', [AbsensiStaffController::class, 'generate'])->name('absensi-staff.generate');
    Route::get('/absensi-staff/{absensiStaff:id}/change', [AbsensiStaffController::class, 'change'])->name('absensi-staff.change');
    Route::resource('absensi-staff', AbsensiStaffController::class);

    // Route Setting
    Route::post('setting-update-waktu/{id}', [DashboardController::class, 'updateWaktu'])->name('setting.update.waktu');
    Route::post('setting-update-pesan/{id}', [DashboardController::class, 'updatePesan'])->name('setting.update.pesan');
    Route::get('setting', [DashboardController::class, 'setting'])->name('setting');
});

// Route::get('/install', function () {
//     shell_exec('composer install');
//     shell_exec('cp .env.example .env');
//     Artisan::call('key:generate');
//     Artisan::call('migrate:fresh --seed');
//     Artisan::call('storage:link');
//     Artisan::call('cache:clear');
// });

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $guarded = [];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function device()
    {
        return $this->belongsTo(Device::class);
    }

    public function jadwal()
    {
        return $this->hasOne(Jadwal::class, 'user_id');
    }

    public function absensiStaff()
    {
        return $this->hasMany(AbsensiStaff::class, 'user_id');
    }

    public function absensi()
    {
        return $this->hasOne(Absensi::class, 'edited_by');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Imports\StaffImport;
use App\Models\Jadwal;
use App\Models\Rfid;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Maatwebsite\Excel\Facades\Excel;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    public function index()
    {
        auth()->user()->can('user-access') ? true : abort(403);

        if (auth()->user()->id == 1) {
            $users = User::where('is_active', 1)->get();
        } else {
            $users = User::where('id', '!=', 1)->where('is_active', 1)->get();
        }

        return view('users.index', compact('users'));
    }

    public function create()
    {
        auth()->user()->can('user-create') ? true : abort(403);

        $user = new User();
        $roles = Role::where('name', '!=', 'Me')->get();
        $jabatan = ['Bimbingan Konseling', 'Guru Mata Pelajaran', 'Kepala Sekolah SMP', 'Kepala Sekolah SMK', 'Laboran', 'Tata Usaha', 'Pembina Osis', 'Wali Kelas', 'Wali Murid', 'Wakil Kepala Sekolah Hubungan Masyarakat', 'Wakil Kepala Sekolah Sarana Prasarana', 'Wakil Kepala Sekolah Kesiswaan', 'Wakil Kepala Sekolah Kurikulum', 'Yayasan'];
        $act = 'create';

        return view('users.create', compact('user', 'roles', 'jabatan', 'act'));
    }

    public function store(Request $request)
    {
        auth()->user()->can('user-create') ? true : abort(403);

        $request->validate([
            'username' => 'required|unique:users',
            'nama' => 'required',
            'westin_id' => 'required',
            'jabatan' => 'required',
            'gender' => 'required',
            'role' => 'required',
            'foto.*' => 'required|mimes:png, jpg, jpeg',
        ]);

        try {
            DB::beginTransaction();
            $foto = $request->file('foto');
            $fotoUrl = $foto->storeAs('images/user', date('YmdHis') . '-' . Str::slug($request->nama) . '.' . $foto->extension());

            $user = User::create([
                'username' => $request->username,
                'nama' => $request->nama,
                'rfid' => $request->rfid ?? '',
                'nik' => $request->westin_id,
                'gender' => $request->gender,
                'password' => bcrypt($request->westin_id),
                'jabatan' => $request->jabatan,
                'foto' => $fotoUrl
            ]);

            Jadwal::create(['user_id' => $user->id]);

            $user->assignRole($request->role);

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('user.index')->with('error', $th->getMessage());
        }
    }

    public function show(User $user)
    {
        //
    }

    public function edit(User $user)
    {
        auth()->user()->can('user-edit') ? true : abort(403);

        $roles = Role::where('name', '!=', 'Me')->get();
        $jabatan = ['Bimbingan Konseling', 'Guru Mata Pelajaran', 'Kepala Sekolah SMP', 'Kepala Sekolah SMK', 'Laboran', 'Tata Usaha', 'Pembina Osis', 'Wali Kelas', 'Wali Murid', 'Wakil Kepala Sekolah Hubungan Masyarakat', 'Wakil Kepala Sekolah Sarana Prasarana', 'Wakil Kepala Sekolah Kesiswaan', 'Wakil Kepala Sekolah Kurikulum', 'Yayasan'];

        $act = 'edit';

        return view('users.edit', compact('user', 'roles', 'jabatan', 'act'));
    }

    public function update(Request $request, User $user)
    {
        auth()->user()->can('user-edit') ? true : abort(403);

        $request->validate([
            'username' => 'required|unique:users,username,' . $user->id,
            'nama' => 'required',
            'westin_id' => 'required',
            'gender' => 'required',
            'jabatan' => 'required',
            'role' => 'required',
            'foto.*' => 'mimes:png, jpg, jpeg',
        ]);

        try {
            DB::beginTransaction();
            if ($request->file('foto')) {
                Storage::delete($user->foto);
                $foto = $request->file('foto');
                $fotoUrl = $foto->storeAs('images/user', date('YmdHis') . '-' . Str::slug($request->nama) . '.' . $foto->extension());
                move_uploaded_file($foto->getClientOriginalName(), asset('strg/images/user'));
            } else {
                $fotoUrl = $user->foto;
            }

            if ($user->rfid == NULL) {
                if ($request->rfid) {
                    $device = Rfid::where('rfid', $request->rfid)->first();
                    $device->update(['status' => 0]);
                    $device_id = $device->id;
                } else {
                    $device_id = 0;
                }
            }

            if ($request->password) {
                $password = bcrypt($request->password);
            } else {
                $password = $user->password;
            }

            $user->update([
                'username' => $request->username,
                'nama' => $request->nama,
                'nik' => $request->westin_id,
                'gender' => $request->gender,
                'password' => $password,
                'jabatan' => $request->jabatan,
                'rfid' => $request->rfid ?? '',
                'device_id' => $device_id ?? $user->device_id,
                'foto' => $fotoUrl
            ]);

            $user->syncRoles($request->role);

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('user.index')->with('error', $th->getMessage());
        }
    }

    public function destroy(User $user)
    {
        auth()->user()->can('user-delete') ? true : abort(403);

        try {
            DB::beginTransaction();

            // Storage::delete($user->foto);
            $user->update(['is_active' => 0, 'is_login' => 0]);

            DB::commit();

            return redirect()->route('user.index')->with('success', 'User berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('user.index')->with('error', $th->getMessage());
        }
    }

    public function import(Request $request)
    {
        $request->validate([
            'file' => 'required',
            'file.*' => 'mimes:xlsx, xls, csv'
        ]);

        try {
            DB::beginTransaction();

            Excel::import(new StaffImport, $request->file('file'));

            DB::commit();

            return redirect()->route('user.index')->with('success', 'Data berhasil diimport');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('user.index')->with('error', $th->getMessage());
        }
    }

    public function dump()
    {
        auth()->user()->can('dump-user-access') ? true : abort(403);

        if (auth()->user()->id == 1) {
            $users = User::where('is_active', 0)->get();
        } else {
            $users = User::where('id', '!=', 1)->where('is_active', 0)->get();
        }

        return view('users.dump', compact('users'));
    }

    public function status(User $user)
    {
        try {
            DB::beginTransaction();

            $user->update(['is_login' => 1, 'is_active' => 1]);

            DB::commit();

            return back()->with('success', 'User berhasil diaktifkan kembali');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function islogin()
    {
        try {
            DB::beginTransaction();
            $user = User::find(request('id'));

            $user->update([
                'is_login' => $user->is_login == 1 ? 0 : 1
            ]);

            DB::commit();

            return response()->json([
                'message' => 'Access login user berhasil diupdate'
            ]);
        } catch (\Throwable $th) {
            return response()->json([
                'message' => $th->getMessage()
            ]);
        }
    }

    public function download()
    {
        return Response::download('excel/example-format-staff.xlsx');
    }

    public function delete(User $user)
    {
        try {
            DB::beginTransaction();
            foreach ($user->absensiStaff as $absen) {
                $absen->delete();
            }
            $user->jadwal->delete();

            $user->delete();

            DB::commit();

            return back()->with('success', 'Data Staff berhasil dihapus secara permanen');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/users/create.blade.php
@extends('layouts.master', ['title' => 'Create User'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Create User</div>

            <div class="card-body">
                <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('users.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    setInterval(function() {
        $.ajax({
            method: 'GET',
            type: 'GET',
            url: '{{ route("rfid.show", 1) }}',
            success: function(response) {
                $("#rfid").val(response.rfid.rfid)
            }
        })
    }, 2000)
</script>
@endpush

resources/views/users/dump.blade.php
@extends('layouts.master', ['title' => 'Data Dump User'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-stats card-danger card-round">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <div class="icon-big text-center">
                            <i class="fas fa-exclamation-triangle"></i>
                        </div>
                    </div>
                    <div class="col-10 col-stats">
                        <div class="numbers">
                            <h4 class="card-title">Warning</h4>
                            <p class="card-category">
                                Data staff yang dihapus dari sini bersifat permanen & semua data absensi staff juga akan ikut terhapus !
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">Data Dump User</div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Foto</th>
                                <th>RFID</th>
                                <th>Username</th>
                                <th>West ID</th>
                                <th>Nama</th>
                                <th>Jabatan</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <div class="avatar avatar-l">
                                        <img src="{{ asset('storage/' . $user->foto ) }}" alt="" class="avatar-img rounded-circle">
                                    </div>
                                </td>
                                <td>{{ $user->rfid }}</td>
                                <td>{{ $user->username }}</td>
                                <td>{{ $user->nik }}</td>
                                <td>{{ $user->nama }}</td>
                                <td>{{ $user->jabatan }}</td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{{ route('user.status', $user->id) }}" class="btn btn-sm btn-success mr-1" onclick="return confirm('Aktifkan kembali User?')"><i class="fas fa-check"></i></a>

                                        <form action="{{ route('user.delete', $user->id) }}" method="post" class="form-delete">
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-danger btn-delete"><i class="fas fa-times"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@stop

@push('script')
<script>
    $(".table").DataTable()
</script>
@endpush

resources/views/users/edit.blade.php
@extends('layouts.master', ['title' => 'Edit User'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Edit User</div>

            <div class="card-body">
                <form action="{{ route('user.update', $user->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    @include('users.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    setInterval(function() {
        $.ajax({
            method: 'GET',
            type: 'GET',
            url: '{{ route("rfid.show", 1) }}',
            success: function(response) {
                $("#rfid").val(response.rfid.rfid)
            }
        })
    }, 2000)
</script>
@endpush

resources/views/users/form.blade.php
<div class="form-group">
    <label for="username">Username</label>
    <input type="text" name="username" id="username" class="form-control" value="{{ $user->username ?? old('username') }}">

    @error('username')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="nama" id="nama" class="form-control" value="{{ $user->nama ?? old('nama') }}">

    @error('nama')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

@if($act == 'edit')
<div class="form-group">
    <label for="password">Password</label>
    <input type="password" name="password" id="password" class="form-control">

    @error('password')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
@endif

<div class="form-group">
    <label for="westin_id">ID Guru / Staff</label>
    <input type="text" name="westin_id" id="westin_id" class="form-control" value="{{ $user->nik ?? old('westin_id') }}">

    @error('westin_id')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="gender">Gender</label>
    <select name="gender" id="gender" class="form-control">
        <option disabled selected>-- Pilih gender --</option>
        <option {{ $user->gender == 'Laki - Laki' ? 'selected' : '' }} value="Laki - Laki">Laki - Laki</option>
        <option {{ $user->gender == 'Perempuan' ? 'selected' : '' }} value="Perempuan">Perempuan</option>
    </select>

    @error('gender')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="jabatan">Jabatan</label>
    <select name="jabatan" id="jabatan" class="form-control">
        <option disabled selected>-- Pilih Jabatan --</option>
        @foreach($jabatan as $jb)
        <option {{ $jb == $user->jabatan ? 'selected' : '' }} value="{{ $jb }}">{{ $jb }}</option>
        @endforeach
    </select>

    @error('jabatan')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="role">Role</label>
    <select name="role" id="role" class="form-control">
        <option disabled selected>-- Pilih role --</option>
        @foreach($roles as $role)
        <option {{ $user->id && $role->id == $user->roles()->first()->id ? 'selected' : '' }} value="{{ $role->id }}">{{ $role->name }}</option>
        @endforeach
    </select>

    @error('role')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="rfid">RFID</label>
    <input type="text" name="rfid" id="rfid" class="form-control" value="{{ $user->rfid ?? old('rfid') }}">

    @error('rfid')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="foto">Foto</label>
    <input type="file" name="foto" id="foto" class="form-control">

    @error('foto')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-danger">Submit</button>
</div>

resources/views/users/index.blade.php
@extends('layouts.master', ['title' => 'Data User Aktif'])

@push('style')
<!-- Datatable -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">
@endpush

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Data User Aktif</div>

            <div class="card-body">
                <a href="{{ route('user.create') }}" class="btn btn-danger mb-3">Tambah User</a>
                <a href="{{ route('user.download') }}" class="btn btn-success mb-3"><i class="fas fa-download"></i> Example Format</a>
                <button type="button" class="btn mb-3 btn-info btn-import" data-toggle="modal" data-target="#modalImport">
                    <i class="fas fa-upload"></i> Import
                </button>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>No</th>
                                <th>Foto</th>
                                <th>RFID</th>
                                <th>Username</th>
                                <th>ID</th>
                                <th>Nama</th>
                                <th>Jabatan / Role</th>
                                <th>Access Login</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($users as $user)
                            <tr>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $loop->iteration }}</td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $loop->iteration }}</td>
                                <td>
                                    <div class="avatar avatar-l">
                                        <img src="{{ asset('storage/' . $user->foto ) }}" alt="" class="avatar-img rounded-circle">
                                    </div>
                                </td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $user->rfid }}</td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $user->username }}</td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $user->nik }}</td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $user->nama }}</td>
                                <td class="{{ $user->is_login == 0 ? 'text-danger' : '' }}">{{ $user->jabatan }} / {{ $user->roles()->first()->name ?? '-' }}</td>
                                <td class="text-center">
                                    <input type="checkbox" id="{{ $user->id }}" class="islogin" {{ $user->is_login == 1 ? 'checked' : '' }}>
                                </td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-success mr-1"><i class="fas fa-edit"></i></a>
                                        <form action="{{ route('user.destroy', $user->id) }}" method="post" class="form-delete">
                                            @method('DELETE')
                                            @csrf
                                            <button type="submit" class="btn btn-danger btn-sm btn-delete"><i class="fas fa-trash"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="modalImport" tabindex="-1" aria-labelledby="modalImportLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalImportLabel">Import Data Staff</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form action="{{ route('user.import') }}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <div class="form-gruop">
                        <label for="file">File Excel</label>
                        <input type="file" name="file" id="file" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-sm btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
</div>
@stop

@push('script')
<!-- Datatable -->
<script src="https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap.min.js"></script>

<script>
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });

    var table = $('.table').DataTable({
        responsive: {
            details: {
                type: 'column'
            }
        },
        columnDefs: [{
            className: 'dtr-control',
            responsivePriority: 1,
            targets: 0
        }, ]
    });

    new $.fn.dataTable.FixedHeader(table);


    $(".table").on('click', '.islogin', function() {
        let id = $(this).attr('id')
        $.ajax({
            url: '{{ route("user.islogin") }}',
            type: 'GET',
            data: {
                id: id,
            },
            success: function(response) {
                swal("Selamat!", response.message, {
                    icon: "success",
                    buttons: {
                        confirm: {
                            className: 'btn btn-success'
                        }
                    },
                });
            },
        })
    })
</script>
@endpush