routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AbsensiStaffController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RfidController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['auth', 'isLogin'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/update', [DashboardController::class, 'update'])->name('profile.update');

    //Route Data Permission
    Route::resource('permission', PermissionController::class);

    //Route Data Role
    Route::resource('role', RoleController::class);

    //Route Data Users
    Route::post('/user/import', [UserController::class, 'import'])->name('user.import');
    Route::get('/user/download', [UserController::class, 'download'])->name('user.download');
    Route::get('/dump/user', [UserController::class, 'dump'])->name('user.dump');
    Route::get('/user/{user:id}/status', [UserController::class, 'status'])->name('user.status');
    Route::get('/user/islogin', [UserController::class, 'islogin'])->name('user.islogin');
    Route::post('/user/{user:id}/delete', [UserController::class, 'delete'])->name('user.delete');
    Route::resource('user', UserController::class);

    //Route Data Kelas
    Route::post('/kelas/import', [KelasController::class, 'import'])->name('kelas.import');
    Route::get('/kelas/download', [KelasController::class, 'download'])->name('kelas.download');
    Route::get('/kelas/siswa', [KelasController::class, 'getSiswa'])->name('kelas.siswa');
    Route::post('/kelas/kenaikan', [KelasController::class, 'kenaikan'])->name('kelas.kenaikan');
    Route::resource('kelas', KelasController::class);

    //Route Data Siswa
    Route::get('/dump/siswa', [SiswaController::class, 'dump'])->name('siswa.dump');
    Route::get('/siswa/{siswa:id}/activated', [SiswaController::class, 'activated'])->name('siswa.activated');
    Route::get('/siswa/{siswa:id}/export', [SiswaController::class, 'export'])->name('siswa.export');
    Route::post('/siswa/{siswa:id}/delete', [SiswaController::class, 'delete'])->name('siswa.delete');
    Route::resource('siswa', SiswaController::class);

    //Route Data Jadwal
    Route::get('/jadwal/set', [JadwalController::class, 'set'])->name('jadwal.set');
    Route::resource('jadwal', JadwalController::class);

    //Route Data Holiday
    Route::resource('holiday', HolidayController::class);

    //Route Data Device
    Route::post('/device/{device:id}/change', [DeviceController::class, 'change'])->name('device.change');
    Route::resource('device', DeviceController::class);

    //Route Data Rfid
    Route::resource('rfid', RfidController::class);

    //Route Data History
    Route::resource('history', HistoryController::class);

    //Route Data Absensi
    Route::get('/absensi/export', [AbsensiController::class, 'export'])->name('absensi.export');
    Route::get('/absensi/report', [AbsensiController::class, 'report'])->name('absensi.report');
    Route::get('/absensi/export-report', [AbsensiController::class, 'generate'])->name('absensi.generate');
    Route::get('/absensi/{absensi:id}/change', [AbsensiController::class, 'change'])->name('absensi.change');
    Route::resource('absensi', AbsensiController::class);

    //Route Data Absensi Staff
    Route::get('/absensi-staff/export', [AbsensiStaffController::class, 'export'])->name('absensi-staff.export');
    Route::get('/absensi-staff/report', [AbsensiStaffController::class, 'report'])->name('absensi-staff.report');
    Route::get('/absensi-staff/export-report', [AbsensiStaffController::class, 'generate'])->name('absensi-staff.generate');
    Route::get('/absensi-staff/{absensiStaff:id}/change', [AbsensiStaffController::class, 'change'])->name('absensi-staff.change');
    Route::resource('absensi-staff', AbsensiStaffController::class);

    // Route Setting
    Route::post('setting-update-waktu/{id}', [DashboardController::class, 'updateWaktu'])->name('setting.update.waktu');
    Route::post('setting-update-pesan/{id}', [DashboardController::class, 'updatePesan'])->name('setting.update.pesan');
    Route::get('setting', [DashboardController::class, 'setting'])->name('setting');
});

// Route::get('/install', function () {
//     shell_exec('composer install');
//     shell_exec('cp .env.example .env');
//     Artisan::call('key:generate');
//     Artisan::call('migrate:fresh --seed');
//     Artisan::call('storage:link');
//     Artisan::call('cache:clear');
// });

app/Models/Siswa.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Siswa extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function kelas()
    {
        return $this->belongsTo(Kelas::class);
    }

    public function device()
    {
        return $this->belongsTo(Device::class);
    }

    public function absensi()
    {
        return $this->hasMany(Absensi::class);
    }
}

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kelas;
use App\Models\Rfid;
use App\Models\Siswa;
use Carbon\CarbonPeriod;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Yajra\Datatables\Datatables;

class SiswaController extends Controller
{
    public function index()
    {
        auth()->user()->can('siswa-access') ? true : abort(403);

        if (request()->ajax()) {
            $data = Siswa::where('is_active', 1)->orderBy('nama', 'ASC')->get();
            dd($data);

            return DataTables::of($data)
                ->addIndexColumn()
                ->editColumn('foto', function ($row) {
                    return '<div class="avatar avatar-l">
                    <img src="' . asset('storage/' . $row->foto) . '" alt="" class="avatar-img rounded-circle">
                </div>';
                })
                ->editColumn('device', function ($row) {
                    return $row->device->nama ?? '-';
                })
                ->editColumn('kelas', function ($row) {
                    return $row->kelas->nama;
                })
                ->editColumn('action', function ($row) {
                    return '<div class="d-flex">
                    <a href="' . route("siswa.edit", $row->id) . '" class="btn btn-sm btn-success mr-1"><i class="fas fa-edit"></i></a>
                    <form action="' . route("siswa.destroy", $row->id) . '" method="post" class="form-delete-' . $row->id . '">
                    ' . csrf_field() . '
                    ' . method_field("DELETE") . '
                        <button type="submit" class="btn btn-danger btn-sm btn-delete" id="' . $row->id . '"><i class="fas fa-trash"></i></button>
                    </form>
                </div>';
                })
                ->rawColumns(['device', 'foto', 'kelas', 'action'])
                ->make(true);
        }

        return view('siswa.index');
    }

    public function create()
    {
        auth()->user()->can('siswa-create') ? true : abort(403);

        $siswa = new Siswa();
        $kelas = Kelas::orderBy('nama', 'ASC')->get();

        return view('siswa.create', compact('siswa', 'kelas'));
    }

    public function store(Request $request)
    {
        auth()->user()->can('siswa-create') ? true : abort(403);

        $request->validate([
            'nisn' => 'required',
            'nama' => 'required',
            'gender' => 'required',
            'kelas' => 'required',
            'no_hp' => 'required',
            'no_hp_ortu' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'alamat' => 'required',
            'foto.*' => 'required|mimes: jpeg, jpg, png',
        ]);

        try {

            DB::beginTransaction();

            $foto = $request->file('foto');
            $fotoUrl = $foto->storeAs('images/siswa', date('YmdHis') . '-' . Str::slug($request->nama) . '.' . $foto->extension());
            Siswa::create([
                'nisn' => $request->nisn,
                'nama' => $request->nama,
                'gender' => $request->gender,
                'tanggal_lahir' => $request->tanggal_lahir,
                'tempat_lahir' => $request->tempat_lahir,
                'no_hp' => $request->no_hp,
                'no_hp_ortu' => $request->no_hp_ortu,
                'alamat' => $request->alamat,
                'kelas_id' => $request->kelas,
                'rfid' => $request->rfid ?? '',
                'foto' => $fotoUrl,
            ]);

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('siswa.index')->with('error', $th->getMessage());
        }
    }

    public function show(Siswa $siswa)
    {
        //
    }

    public function edit(Siswa $siswa)
    {
        auth()->user()->can('siswa-edit') ? true : abort(403);

        $kelas = Kelas::orderBy('nama', 'ASC')->get();

        return view('siswa.edit', compact('siswa', 'kelas'));
    }

    public function update(Request $request, Siswa $siswa)
    {
        auth()->user()->can('siswa-edit') ? true : abort(403);

        $request->validate([
            'nisn' => 'required',
            'nama' => 'required',
            'gender' => 'required',
            'no_hp' => 'required',
            'no_hp_ortu' => 'required',
            'tempat_lahir' => 'required',
            'tanggal_lahir' => 'required',
            'alamat' => 'required',
            'kelas' => 'required',
            'foto.*' => 'required|mimes: jpeg, jpg, png',
        ]);

        try {
            DB::beginTransaction();

            if ($request->file('foto')) {
                Storage::delete($siswa->foto);
                $foto = $request->file('foto');
                $fotoUrl = $foto->storeAs('images/siswa', date('YmdHis') . '-' . Str::slug($request->nama) . '.' . $foto->extension());
            } else {
                $fotoUrl = $siswa->foto;
            }

            if ($request->rfid) {
                $device = Rfid::where('rfid', $request->rfid)->first();
                $device->update(['status' => 0]);
                $device_id = $device->id;
            } else {
                $device_id = 0;
            }

            $siswa->update([
                'nisn' => $request->nisn,
                'nama' => $request->nama,
                'gender' => $request->gender,
                'tanggal_lahir' => $request->tanggal_lahir,
                'tempat_lahir' => $request->tempat_lahir,
                'no_hp' => $request->no_hp,
                'no_hp_ortu' => $request->no_hp_ortu,
                'alamat' => $request->alamat,
                'kelas_id' => $request->kelas,
                'device_id' => $device_id,
                'rfid' => $request->rfid ?? '',
                'foto' => $fotoUrl,
            ]);

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('siswa.index')->with('error', $th->getMessage());
        }
    }

    public function destroy(Siswa $siswa)
    {
        auth()->user()->can('siswa-delete') ? true : abort(403);

        try {
            DB::beginTransaction();

            // Storage::delete($siswa->foto);

            $siswa->update(['is_active' => 0]);

            DB::commit();

            return redirect()->route('siswa.index')->with('success', 'Siswa berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('siswa.index')->with('error', $th->getMessage());
        }
    }

    public function dump()
    {
        auth()->user()->can('dump-siswa-access') ? true : abort(403);

        $siswa = Siswa::where('is_active', 0)->get();

        return view('siswa.dump', compact('siswa'));
    }

    public function activated(Siswa $siswa)
    {
        try {
            DB::beginTransaction();
            $siswa->update(['is_active' => 1]);
            DB::commit();

            return back()->with('success', 'Siswa berhasil diaktifasi kembali');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function export(Siswa $siswa)
    {
        $period = CarbonPeriod::create('2022-02-01', '2022-03-01');

        // Iterate over the period
        foreach ($period as $date) {
            echo $date->format('d') . '<br>';
        }
    }

    public function delete(Siswa $siswa)
    {
        try {
            DB::beginTransaction();
            foreach ($siswa->absensi as $absen) {
                $absen->delete();
            }

            $siswa->delete();

            DB::commit();

            return back()->with('success', 'Data siswa berhasil dihapus secara permanen');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }
}

resources/views/siswa/create.blade.php
@extends('layouts.master', ['title' => 'Create Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Create Siswa</div>

            <div class="card-body">
                <form action="{{ route('siswa.store') }}" method="post" enctype="multipart/form-data">
                    @csrf
                    @include('siswa.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    setInterval(function() {
        $.ajax({
            method: 'GET',
            type: 'GET',
            url: '{{ route("rfid.show", 1) }}',
            success: function(response) {
                $("#rfid").val(response.rfid.rfid)
            }
        })
    }, 2000)
</script>
@endpush

resources/views/siswa/dump.blade.php
@extends('layouts.master', ['title' => 'Data Dump Siswa'])

@push('style')
<!-- Datatable -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">
@endpush

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card card-stats card-danger card-round">
            <div class="card-body">
                <div class="row">
                    <div class="col-2">
                        <div class="icon-big text-center">
                            <i class="fas fa-exclamation-triangle"></i>
                        </div>
                    </div>
                    <div class="col-10 col-stats">
                        <div class="numbers">
                            <h4 class="card-title">Warning</h4>
                            <p class="card-category">
                                Data siswa yang dihapus dari sini bersifat permanen & semua data absensi siswa juga akan ikut terhapus !
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">Data Dump Siswa</div>

            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped" width="100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>No</th>
                                <th>Foto</th>
                                <th>RFID</th>
                                <th>Nisn</th>
                                <th>Nama</th>
                                <th>Gender</th>
                                <th>Kelas</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($siswa as $sw)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $loop->iteration }}</td>
                                <td>
                                    <div class="avatar avatar-l">
                                        <img src="{{ asset('/storage/' . $sw->foto) }}" alt="" class="avatar-img rounded-circle">
                                    </div>
                                </td>
                                <td>{{ $sw->rfid }}</td>
                                <td>{{ $sw->nisn }}</td>
                                <td>{{ $sw->nama }}</td>
                                <td>{{ $sw->gender }}</td>
                                <td>{{ $sw->kelas->nama }}</td>
                                <td>
                                    <div class="d-flex">
                                        <a href="{{ route('siswa.activated', $sw->id) }}" class="btn btn-sm btn-success mr-1" onclick="return confirm('Aktifkan kembali siswa ?')"><i class="fas fa-check"></i></a>

                                        <form action="{{ route('siswa.delete', $sw->id) }}" method="post" class="form-delete">
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-danger btn-delete"><i class="fas fa-times"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<!-- Datatable -->
<script src=" https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js">
</script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var table = $('.table').DataTable({
            responsive: {
                details: {
                    type: 'column'
                }
            },
            columnDefs: [{
                className: 'dtr-control',
                responsivePriority: 1,
                targets: 0
            }, ]
        });

        new $.fn.dataTable.FixedHeader(table);
    });
</script>
@endpush

resources/views/siswa/edit.blade.php
@extends('layouts.master', ['title' => 'Edit Siswa'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Edit Siswa</div>

            <div class="card-body">
                <form action="{{ route('siswa.update', $siswa->id) }}" method="post" enctype="multipart/form-data">
                    @method('PATCH')
                    @csrf
                    @include('siswa.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script>
    setInterval(function() {
        $.ajax({
            method: 'GET',
            type: 'GET',
            url: '{{ route("rfid.show", 1) }}',
            success: function(response) {
                $("#rfid").val(response.rfid.rfid)
            }
        })
    }, 2000)
</script>
@endpush

resources/views/siswa/form.blade.php
<div class="form-group">
    <label for="nisn">Nisn</label>
    <input type="text" name="nisn" id="nisn" class="form-control" value="{{ $siswa->nisn ?? old('nisn') }}">

    @error('nisn')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="nama" id="nama" class="form-control"
        value="{{ $siswa->nama ?? old('nama') }}">

    @error('nama')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="gender">Gender</label>
    <select name="gender" id="gender" class="form-control">
        <option disabled selected>-- Pilih gender --</option>
        <option {{ $siswa->gender == 'Laki - Laki' ? 'selected' : '' }} value="Laki - Laki">Laki - Laki</option>
        <option {{ $siswa->gender == 'Perempuan' ? 'selected' : '' }} value="Perempuan">Perempuan</option>
    </select>

    @error('gender')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>


<div class="form-group">
    <label for="kelas">Kelas</label>
    <select name="kelas" id="kelas" class="form-control">
        <option disabled selected>-- Pilih Kelas --</option>
        @foreach ($kelas as $kls)
            <option {{ $siswa->id && $kls->id == $siswa->kelas->id ? 'selected' : '' }} value="{{ $kls->id }}">
                {{ $kls->nama }}</option>
        @endforeach
    </select>

    @error('kelas')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="tempat_lahir">Tempat Lahir</label>
    <input type="text" name="tempat_lahir" id="tempat_lahir" class="form-control"
        value="{{ $siswa->tempat_lahir ?? old('tempat_lahir') }}">

    @error('tempat_lahir')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="tanggal_lahir">Tanggal Lahir</label>
    <input type="date" name="tanggal_lahir" id="tanggal_lahir" class="form-control"
        value="{{ $siswa->tanggal_lahir ?? old('tanggal_lahir') }}">

    @error('tanggal_lahir')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="alamat">Alamat</label>
    <textarea name="alamat" id="alamat" rows="5"  class="form-control">
        {{ $siswa->alamat ?? old('alamat') }}
    </textarea>

    @error('alamat')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="no_hp">No HP</label>
    <input type="number" name="no_hp" id="no_hp" class="form-control"
        value="{{ $siswa->no_hp ?? old('no_hp') }}">

    @error('no_hp')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>
<div class="form-group">
    <label for="no_hp_ortu">No HP ortu</label>
    <input type="text" name="no_hp_ortu" id="no_hp_ortu" class="form-control"
        value="{{ $siswa->no_hp_ortu ?? old('no_hp_ortu') }}">

    @error('no_hp_ortu')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>


<div class="form-group">
    <label for="rfid">Rfid</label>
    <input type="text" name="rfid" id="rfid" class="form-control"
        value="{{ $siswa->rfid ?? old('rfid') }}">

    @error('rfid')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="foto">Foto</label>
    <input type="file" name="foto" id="foto" class="form-control">

    @error('foto')
        <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-danger">Submit</button>
</div>

resources/views/siswa/index.blade.php
@extends('layouts.master', ['title' => 'Data Siswa'])

@push('style')
<!-- Datatable -->
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.23/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.6/css/responsive.bootstrap4.min.css">
@endpush

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Data Siswa</div>

            <div class="card-body">
                <a href="{{ route('siswa.create') }}" class="btn btn-danger mb-3">Tambah Siswa</a>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped" width="100%">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>No</th>
                                <th>Foto</th>
                                <th>RFID</th>
                                <th>Nisn</th>
                                <th>Nama</th>
                                <th>Gender</th>
                                <th>Kelas</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<!-- Datatable -->
<script src=" https://cdn.datatables.net/1.10.23/js/jquery.dataTables.min.js">
</script>
<script src="https://cdn.datatables.net/1.10.23/js/dataTables.bootstrap4.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.6/js/responsive.bootstrap.min.js"></script>

<script>
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var table = $('.table').DataTable({
            processing: true,
            serverSide: true,
            orderable: true,
            searchable: true,
            ajax: "{{ route('siswa.index') }}",
            columns: [{
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'DT_RowIndex',
                    name: 'DT_RowIndex'
                },
                {
                    data: 'foto',
                    name: 'foto'
                },
                {
                    data: 'rfid',
                    name: 'rfid'
                },
                {
                    data: 'nisn',
                    name: 'nisn'
                },
                {
                    data: 'nama',
                    name: 'nama'
                },
                {
                    data: 'gender',
                    name: 'gender'
                },
                {
                    data: 'kelas',
                    name: 'kelas'
                },
                {
                    data: 'action',
                    name: 'action'
                },
            ],
            responsive: {
                details: {
                    type: 'column'
                }
            },
            columnDefs: [{
                className: 'dtr-control',
                responsivePriority: 1,
                targets: 0
            }, ]
        });

        new $.fn.dataTable.FixedHeader(table);

        $('.table').on('click', '.btn-delete', function(e) {
            e.preventDefault();
            let id = $(this).attr('id');

            swal({
                title: 'Hapus data?',
                text: "Data yang dihapus bersifat permanen!",
                type: 'warning',
                buttons: {
                    confirm: {
                        text: 'Ya, Hapus!',
                        className: 'btn btn-success'
                    },
                    cancel: {
                        text: 'Batal',
                        visible: true,
                        className: 'btn btn-danger'
                    }
                }
            }).then((response) => {
                if (response) {
                    $(".form-delete-" + id).submit()
                } else {
                    swal.close();
                }
            });
        });
    });
</script>
@endpush