routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AbsensiStaffController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RfidController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['auth', 'isLogin'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/update', [DashboardController::class, 'update'])->name('profile.update');

    //Route Data Permission
    Route::resource('permission', PermissionController::class);

    //Route Data Role
    Route::resource('role', RoleController::class);

    //Route Data Users
    Route::post('/user/import', [UserController::class, 'import'])->name('user.import');
    Route::get('/user/download', [UserController::class, 'download'])->name('user.download');
    Route::get('/dump/user', [UserController::class, 'dump'])->name('user.dump');
    Route::get('/user/{user:id}/status', [UserController::class, 'status'])->name('user.status');
    Route::get('/user/islogin', [UserController::class, 'islogin'])->name('user.islogin');
    Route::post('/user/{user:id}/delete', [UserController::class, 'delete'])->name('user.delete');
    Route::resource('user', UserController::class);

    //Route Data Kelas
    Route::post('/kelas/import', [KelasController::class, 'import'])->name('kelas.import');
    Route::get('/kelas/download', [KelasController::class, 'download'])->name('kelas.download');
    Route::get('/kelas/siswa', [KelasController::class, 'getSiswa'])->name('kelas.siswa');
    Route::post('/kelas/kenaikan', [KelasController::class, 'kenaikan'])->name('kelas.kenaikan');
    Route::resource('kelas', KelasController::class);

    //Route Data Siswa
    Route::get('/dump/siswa', [SiswaController::class, 'dump'])->name('siswa.dump');
    Route::get('/siswa/{siswa:id}/activated', [SiswaController::class, 'activated'])->name('siswa.activated');
    Route::get('/siswa/{siswa:id}/export', [SiswaController::class, 'export'])->name('siswa.export');
    Route::post('/siswa/{siswa:id}/delete', [SiswaController::class, 'delete'])->name('siswa.delete');
    Route::resource('siswa', SiswaController::class);

    //Route Data Jadwal
    Route::get('/jadwal/set', [JadwalController::class, 'set'])->name('jadwal.set');
    Route::resource('jadwal', JadwalController::class);

    //Route Data Holiday
    Route::resource('holiday', HolidayController::class);

    //Route Data Device
    Route::post('/device/{device:id}/change', [DeviceController::class, 'change'])->name('device.change');
    Route::resource('device', DeviceController::class);

    //Route Data Rfid
    Route::resource('rfid', RfidController::class);

    //Route Data History
    Route::resource('history', HistoryController::class);

    //Route Data Absensi
    Route::get('/absensi/export', [AbsensiController::class, 'export'])->name('absensi.export');
    Route::get('/absensi/report', [AbsensiController::class, 'report'])->name('absensi.report');
    Route::get('/absensi/export-report', [AbsensiController::class, 'generate'])->name('absensi.generate');
    Route::get('/absensi/{absensi:id}/change', [AbsensiController::class, 'change'])->name('absensi.change');
    Route::resource('absensi', AbsensiController::class);

    //Route Data Absensi Staff
    Route::get('/absensi-staff/export', [AbsensiStaffController::class, 'export'])->name('absensi-staff.export');
    Route::get('/absensi-staff/report', [AbsensiStaffController::class, 'report'])->name('absensi-staff.report');
    Route::get('/absensi-staff/export-report', [AbsensiStaffController::class, 'generate'])->name('absensi-staff.generate');
    Route::get('/absensi-staff/{absensiStaff:id}/change', [AbsensiStaffController::class, 'change'])->name('absensi-staff.change');
    Route::resource('absensi-staff', AbsensiStaffController::class);

    // Route Setting
    Route::post('setting-update-waktu/{id}', [DashboardController::class, 'updateWaktu'])->name('setting.update.waktu');
    Route::post('setting-update-pesan/{id}', [DashboardController::class, 'updatePesan'])->name('setting.update.pesan');
    Route::get('setting', [DashboardController::class, 'setting'])->name('setting');
});

// Route::get('/install', function () {
//     shell_exec('composer install');
//     shell_exec('cp .env.example .env');
//     Artisan::call('key:generate');
//     Artisan::call('migrate:fresh --seed');
//     Artisan::call('storage:link');
//     Artisan::call('cache:clear');
// });

app/Models/Holiday.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Holiday extends Model
{
    use HasFactory;
    protected $guarded = [];
}

app/Http/Controllers/HolidayController.php
<?php

namespace App\Http\Controllers;

use App\Models\Holiday;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HolidayController extends Controller
{
    public function index()
    {
        auth()->user()->can('holiday-access') ? true : abort(403);

        $holidays = Holiday::get();

        return view('holiday.index', compact('holidays'));
    }

    public function create()
    {
        auth()->user()->can('holiday-create') ? true : abort(403);

        $holiday = new Holiday();

        return view('holiday.create', compact('holiday'));
    }

    public function store(Request $request)
    {
        auth()->user()->can('holiday-create') ? true : abort(403);

        $request->validate([
            'nama' => 'required',
            'waktu' => 'required',
        ]);

        try {
            DB::beginTransaction();

            Holiday::create($request->all());

            DB::commit();

            return redirect()->route('holiday.index')->with('success', 'Data holiday berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('holiday.index')->with('error', $th->getMessage());
        }
    }

    public function show(Holiday $holiday)
    {
        //
    }

    public function edit(Holiday $holiday)
    {
        auth()->user()->can('user-edit') ? true : abort(403);

        return view('holiday.edit', compact('holiday'));
    }

    public function update(Request $request, Holiday $holiday)
    {
        auth()->user()->can('holiday-edit') ? true : abort(403);

        $request->validate([
            'nama' => 'required',
            'waktu' => 'required',
        ]);

        try {
            DB::beginTransaction();

            $holiday->update($request->all());

            DB::commit();

            return redirect()->route('holiday.index')->with('success', 'Data holiday berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('holiday.index')->with('error', $th->getMessage());
        }
    }

    public function destroy(Holiday $holiday)
    {
        auth()->user()->can('holiday-delete') ? true : abort(403);

        try {
            DB::beginTransaction();

            $holiday->delete();

            DB::commit();

            return redirect()->route('holiday.index')->with('success', 'Data holiday berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('holiday.index')->with('error', $th->getMessage());
        }
    }
}

resources/views/holiday/create.blade.php
@extends('layouts.master', ['title' => 'Create Holiday'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Create Holiday</div>

            <div class="card-body">
                <form action="{{ route('holiday.store') }}" method="post">
                    @csrf
                    @include('holiday.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/holiday/edit.blade.php
@extends('layouts.master', ['title' => 'Edit Holiday'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Edit Holiday</div>

            <div class="card-body">
                <form action="{{ route('holiday.update', $holiday->id) }}" method="post">
                    @method('PATCH')
                    @csrf
                    @include('holiday.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/holiday/form.blade.php
<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="nama" id="nama" class="form-control" value="{{ $holiday->nama ?? old('nama') }}" autofocus>

    @error('nama')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <label for="waktu">Waktu</label>
    <input type="date" name="waktu" id="waktu" class="form-control" value="{{ $holiday->waktu ?? old('waktu') }}" autofocus>

    @error('waktu')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-danger">Submit</button>
</div>

resources/views/holiday/index.blade.php
@extends('layouts.master', ['title' => 'Data Holiday'])

@push('style')
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">

<style>
    .toggle.ios,
    .toggle-on.ios,
    .toggle-off.ios {
        border-radius: 20rem;
    }

    .toggle.ios .toggle-handle {
        border-radius: 20rem;
    }
</style>
@endpush

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Data Holiday</div>

            <div class="card-body">
                <a href="{{ route('holiday.create') }}" class="btn btn-danger mb-3">Tambah Holiday</a>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Nama</th>
                                <th>Waktu</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($holidays as $holiday)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $holiday->nama }}</td>
                                <td>{{ Carbon\Carbon::parse($holiday->waktu)->format('d/m/Y') }}</td>
                                <td>
                                    <a href="{{ route('holiday.edit', $holiday->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>
                                    <form action="{{ route('holiday.destroy', $holiday->id) }}" method="post" style="display: inline;" class="form-delete">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger btn-delete"><i class="fas fa-trash"></i></button>
                                    </form>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<script>
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(".table").DataTable();
    })
</script>
@endpush