routes/web.php
<?php

use App\Http\Controllers\AbsensiController;
use App\Http\Controllers\AbsensiStaffController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\DeviceController;
use App\Http\Controllers\HistoryController;
use App\Http\Controllers\HolidayController;
use App\Http\Controllers\JadwalController;
use App\Http\Controllers\KelasController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RfidController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes(['register' => false]);

Route::middleware(['auth', 'isLogin'])->group(function () {
    // Dashboard
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/profile', [DashboardController::class, 'profile'])->name('profile');
    Route::post('/profile/update', [DashboardController::class, 'update'])->name('profile.update');

    //Route Data Permission
    Route::resource('permission', PermissionController::class);

    //Route Data Role
    Route::resource('role', RoleController::class);

    //Route Data Users
    Route::post('/user/import', [UserController::class, 'import'])->name('user.import');
    Route::get('/user/download', [UserController::class, 'download'])->name('user.download');
    Route::get('/dump/user', [UserController::class, 'dump'])->name('user.dump');
    Route::get('/user/{user:id}/status', [UserController::class, 'status'])->name('user.status');
    Route::get('/user/islogin', [UserController::class, 'islogin'])->name('user.islogin');
    Route::post('/user/{user:id}/delete', [UserController::class, 'delete'])->name('user.delete');
    Route::resource('user', UserController::class);

    //Route Data Kelas
    Route::post('/kelas/import', [KelasController::class, 'import'])->name('kelas.import');
    Route::get('/kelas/download', [KelasController::class, 'download'])->name('kelas.download');
    Route::get('/kelas/siswa', [KelasController::class, 'getSiswa'])->name('kelas.siswa');
    Route::post('/kelas/kenaikan', [KelasController::class, 'kenaikan'])->name('kelas.kenaikan');
    Route::resource('kelas', KelasController::class);

    //Route Data Siswa
    Route::get('/dump/siswa', [SiswaController::class, 'dump'])->name('siswa.dump');
    Route::get('/siswa/{siswa:id}/activated', [SiswaController::class, 'activated'])->name('siswa.activated');
    Route::get('/siswa/{siswa:id}/export', [SiswaController::class, 'export'])->name('siswa.export');
    Route::post('/siswa/{siswa:id}/delete', [SiswaController::class, 'delete'])->name('siswa.delete');
    Route::resource('siswa', SiswaController::class);

    //Route Data Jadwal
    Route::get('/jadwal/set', [JadwalController::class, 'set'])->name('jadwal.set');
    Route::resource('jadwal', JadwalController::class);

    //Route Data Holiday
    Route::resource('holiday', HolidayController::class);

    //Route Data Device
    Route::post('/device/{device:id}/change', [DeviceController::class, 'change'])->name('device.change');
    Route::resource('device', DeviceController::class);

    //Route Data Rfid
    Route::resource('rfid', RfidController::class);

    //Route Data History
    Route::resource('history', HistoryController::class);

    //Route Data Absensi
    Route::get('/absensi/export', [AbsensiController::class, 'export'])->name('absensi.export');
    Route::get('/absensi/report', [AbsensiController::class, 'report'])->name('absensi.report');
    Route::get('/absensi/export-report', [AbsensiController::class, 'generate'])->name('absensi.generate');
    Route::get('/absensi/{absensi:id}/change', [AbsensiController::class, 'change'])->name('absensi.change');
    Route::resource('absensi', AbsensiController::class);

    //Route Data Absensi Staff
    Route::get('/absensi-staff/export', [AbsensiStaffController::class, 'export'])->name('absensi-staff.export');
    Route::get('/absensi-staff/report', [AbsensiStaffController::class, 'report'])->name('absensi-staff.report');
    Route::get('/absensi-staff/export-report', [AbsensiStaffController::class, 'generate'])->name('absensi-staff.generate');
    Route::get('/absensi-staff/{absensiStaff:id}/change', [AbsensiStaffController::class, 'change'])->name('absensi-staff.change');
    Route::resource('absensi-staff', AbsensiStaffController::class);

    // Route Setting
    Route::post('setting-update-waktu/{id}', [DashboardController::class, 'updateWaktu'])->name('setting.update.waktu');
    Route::post('setting-update-pesan/{id}', [DashboardController::class, 'updatePesan'])->name('setting.update.pesan');
    Route::get('setting', [DashboardController::class, 'setting'])->name('setting');
});

// Route::get('/install', function () {
//     shell_exec('composer install');
//     shell_exec('cp .env.example .env');
//     Artisan::call('key:generate');
//     Artisan::call('migrate:fresh --seed');
//     Artisan::call('storage:link');
//     Artisan::call('cache:clear');
// });

app/Models/Device.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
    use HasFactory;
    protected $guarded = [];

    public function user()
    {
        return $this->hasMany(User::class);
    }

    public function siswa()
    {
        return $this->hasMany(Siswa::class);
    }

    public function absensi()
    {
        return $this->hasMany(Absensi::class);
    }

    public function history()
    {
        return $this->hasMany(History::class);
    }

    public function rfid()
    {
        return $this->hasMany(Rfid::class);
    }
}

app/Http/Controllers/DeviceController.php
<?php

namespace App\Http\Controllers;

use App\Models\Device;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class DeviceController extends Controller
{
    public function index()
    {
        auth()->user()->can('device-access') ? true : abort(403);

        $devices = Device::get();

        return view('device.index', compact('devices'));
    }

    public function create()
    {
        auth()->user()->can('device-access') ? true : abort(403);

        $device = new Device();

        return view('device.create', compact('device'));
    }

    public function store(Request $request)
    {
        auth()->user()->can('device-access') ? true : abort(403);

        $request->validate(['nama' => 'required']);

        try {
            DB::beginTransaction();

            Device::create(['nama' => $request->nama]);

            DB::commit();

            return redirect()->route('device.index')->with('success', 'Device berhasil ditambahkan');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('device.index')->with('error', $th->getMessage());
        }
    }

    public function show(Device $device)
    {
        //
    }

    public function edit(Device $device)
    {
        auth()->user()->can('device-access') ? true : abort(403);

        return view('device.edit', compact('device'));
    }

    public function update(Request $request, Device $device)
    {
        auth()->user()->can('device-access') ? true : abort(403);

        $request->validate(['nama' => 'required']);

        try {
            DB::beginTransaction();

            $device->update(['nama' => $request->nama]);

            DB::commit();

            return redirect()->route('device.index')->with('success', 'Device berhasil diupdate');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('device.index')->with('error', $th->getMessage());
        }
    }

    public function destroy(Device $device)
    {
        auth()->user()->can('device-access') ? true : abort(403);

        try {
            DB::beginTransaction();

            $device->delete();

            DB::commit();

            return redirect()->route('device.index')->with('success', 'Device berhasil didelete');
        } catch (\Throwable $th) {
            DB::rollBack();
            return redirect()->route('device.index')->with('error', $th->getMessage());
        }
    }

    public function change(Device $device)
    {
        $device->update([
            'mode' => request('mode')
        ]);

        return response()->json([
            'status' => 'success',
            'message' => 'Mode berhasil diubah',
            'device' => $device
        ]);
    }
}

resources/views/device/create.blade.php
@extends('layouts.master', ['title' => 'Create Device'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Create Device</div>

            <div class="card-body">
                <form action="{{ route('device.store') }}" method="post">
                    @csrf
                    @include('device.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/device/edit.blade.php
@extends('layouts.master', ['title' => 'Edit Device'])

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Edit Device</div>

            <div class="card-body">
                <form action="{{ route('device.update', $device->id) }}" method="post">
                    @method('PATCH')
                    @csrf
                    @include('device.form')
                </form>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/device/form.blade.php
<div class="form-group">
    <label for="nama">Nama</label>
    <input type="text" name="nama" id="nama" class="form-control" value="{{ $device->nama ?? old('nama') }}" autofocus>

    @error('nama')
    <small class="text-danger">{{ $message }}</small>
    @enderror
</div>

<div class="form-group">
    <button type="submit" class="btn btn-danger">Submit</button>
</div>

resources/views/device/index.blade.php
@extends('layouts.master', ['title' => 'Data Device'])

@push('style')
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">

<style>
    .toggle.ios,
    .toggle-on.ios,
    .toggle-off.ios {
        border-radius: 20rem;
    }

    .toggle.ios .toggle-handle {
        border-radius: 20rem;
    }
</style>
@endpush

@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">Data Device</div>

            <div class="card-body">
                <a href="{{ route('device.create') }}" class="btn btn-danger mb-3">Tambah Device</a>

                <div class="table-responsive">
                    <table class="table table-bordered table-striped">
                        <thead>
                            <tr>
                                <th>No</th>
                                <th>Id Device</th>
                                <th>Nama</th>
                                <th>Mode</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @foreach($devices as $device)
                            <tr>
                                <td>{{ $loop->iteration }}</td>
                                <td>{{ $device->id }}</td>
                                <td>{{ $device->nama }}</td>
                                <td class="text-center text-light">
                                    <input type="checkbox" class="mode" id="{{ $device->id }}" value="{{ $device->mode == 'SCAN' ? 'ADD' : 'SCAN' }}" {{ $device->mode == 'SCAN' ? 'checked' : '' }}>
                                </td>
                                <td>
                                    <a href="{{ route('device.edit', $device->id) }}" class="btn btn-sm btn-success"><i class="fas fa-edit"></i></a>
                                    <!-- <form action="{{ route('device.destroy', $device->id) }}" method="post" style="display: inline;" class="form-delete">
                                        @method('DELETE')
                                        @csrf
                                        <button type="submit" class="btn btn-sm btn-danger btn-delete"><i class="fas fa-trash"></i></button>
                                    </form> -->
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

@push('script')
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>

<script>
    $(document).ready(function() {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(".table").DataTable();

        $('.mode').bootstrapToggle({
            on: 'Scan',
            off: 'Add',
            style: 'ios',
            size: 'sm',
        })

        $('.mode').change(function() {
            let id = $(this).attr("id")
            $.ajax({
                method: 'POST',
                type: 'POST',
                url: 'device/' + id + '/change',
                data: {
                    mode: $(this).val()
                },
                success: function(response) {
                    swal("Selamat!", response.message, {
                        icon: "success",
                        buttons: {
                            confirm: {
                                className: 'btn btn-success'
                            }
                        },
                    });
                }
            })

        })
    })
</script>
@endpush